name: "size-limit"
on:
  push:
    branches:
      - main

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check file sizes
        run: |
          find . -type f -not -path './.git/*' -size +50k | while read file; do
            echo "File $file exceeds the 50KB limit"
            echo "Deleting $file"
            git config --global user.email "nara9271@colorado.edu"
            git config --global user.name "GitHub Actions"
            git rm -f $file
            rm -f $file
            git add .
            git commit -m "Remove files larger than 50KB" || echo "No changes to commit"
            git remote -v
            git push origin main
          done
